import Head from 'next/head'
import Footer from '../components/Footer'
import Header from '../components/Header'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.HomeContainer + " container"}>
      <Head>
        <title>Blue Endcode | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <Header />
      <main className={styles.WrapperHome}>
        <div>
          <h1 title='blue endcode software' data-title="SOFTWARE" className={styles.Heading + " " + styles.text}>SOFTWARE</h1>
          <ul className={styles.TabList}>
            <li className={styles.TabItem}>
              <div className={styles.TabName}>
                <span className={styles.FirstLetter}>
                  D
                </span>
                <span className={styles.Light}>esign</span>
              </div>
            </li>
            <li className={styles.Deliver} />
            <li className={styles.TabItem}>
              <div className={styles.TabName}>
                <span className={styles.SecondLetter}>
                  D
                </span>
                <span className={styles.Light}>evelop</span>
              </div>
            </li>
            <li className={styles.Deliver} />
            <li className={styles.TabItem}>
              <div className={styles.TabName}>
                <span className={styles.ThirdLetter}>
                  T
                </span>
                <span className={styles.Light}>est</span>
              </div>
            </li>
            <li className={styles.Deliver} />
            <li className={styles.TabItem}>
              <div className={styles.TabName}>
                <span className={styles.FourLetter}>
                  P
                </span>
                <span className={styles.Light}>roduct</span>
              </div>
            </li>
          </ul>
          <div></div>
          <h1 className={styles.HeadingTwo}>
            Center
          </h1>
        </div>
      </main>
      <Footer />
    </div>
  )
}
